import type { Metadata } from 'next'
import { Roboto_Flex } from 'next/font/google'
import './globals.css'

const robotoFlex = Roboto_Flex({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Fullstack Contact Form with PostgreSQL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={robotoFlex.className}>
      <body>{children}</body>
    </html>
  )
}
